name: pylops-gpu
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6.4
  - numpy>=1.15.0
  - scipy>=1.4.0
  - pytorch>=1.2.0
  - torchvision
  - pylops<=1.13.0
  - pytest
  - Sphinx
  - numpydoc
  - pip:
    - spgl1
    - pytorch-complex-tensor
    - pytest-runner
    - setuptools_scm
    - sphinx-rtd-theme
    - sphinx-gallery
    - nbsphinx
    - image
